version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: amazon_connect_demo_api_dev
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    command: bash -c "npm install && npm run dev & composer install && php artisan serve --host=0.0.0.0 --port=8000"
